version: "3"

services:
  app:
    container_name: gpt-ai-assistant
    build: .
    restart: always
    ports:
      - "172.17.0.1:${APP_PORT}:${APP_PORT}"
    environment:
      - APP_DEBUG=${APP_DEBUG}
      - APP_PORT=${APP_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - OPENAI_COMPLETION_MODEL=${OPENAI_COMPLETION_MODEL}
      - OPENAI_COMPLETION_TEMPERATURE=${OPENAI_COMPLETION_TEMPERATURE}
      - HUMAN_NAME=${HUMAN_NAME}
      - BOT_NAME=${BOT_NAME}
      - HUMAN_INIT_PROMPT=${HUMAN_INIT_PROMPT}
      - BOT_INIT_PROMPT=${BOT_INIT_PROMPT}